# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/messenger.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/messenger.proto\"\x06\n\x04Void\"(\n\x07Message\x12\x0f\n\x07Message\x18\x01 \x01(\t\x12\x0c\n\x04User\x18\x02 \x01(\t2H\n\x04\x43hat\x12 \n\x0bGetMessages\x12\x05.Void\x1a\x08.Message0\x01\x12\x1e\n\x0bSendMessage\x12\x08.Message\x1a\x05.Voidb\x06proto3')



_VOID = DESCRIPTOR.message_types_by_name['Void']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'protos.messenger_pb2'
  # @@protoc_insertion_point(class_scope:Void)
  })
_sym_db.RegisterMessage(Void)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'protos.messenger_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  })
_sym_db.RegisterMessage(Message)

_CHAT = DESCRIPTOR.services_by_name['Chat']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOID._serialized_start=26
  _VOID._serialized_end=32
  _MESSAGE._serialized_start=34
  _MESSAGE._serialized_end=74
  _CHAT._serialized_start=76
  _CHAT._serialized_end=148
# @@protoc_insertion_point(module_scope)
